name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project (Debug|x64)
        run: msbuild dpapi-cli.sln /p:Configuration=Release /p:Platform=x64 /m

      - name: Upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: dpapi-cli-build
          path: dpapi-cli/build/Release_x64/bin/dpapi-cli.exe
          compression-level: 0
          if-no-files-found: error
