name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build project (Release|x64)
        run: msbuild dpapi-cli.sln /p:Configuration=Release /p:Platform=x64 /m

      - name: Upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: dpapi-cli-build
          path: ${{ github.workspace }}/build/Release_x64/bin/dpapi-cli.exe
          compression-level: 0
          if-no-files-found: error

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dpapi-cli-build
          path: build_artifacts

      - name: Get binary version
        id: get_version
        run: |
          version=$(build_artifacts/dpapi-cli.exe --version)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo $version